application:
  title: "REST API documentation"
  version: "0.0.1"
  description: "Приложение по <a href='https://javaops.ru/view/bootjava'>курсу BootJava</a>"
  author:
    contact:
      url: "https://javaops.ru/#contacts"
      name: "Grigory Kislin"
      email: "admin@javaops.ru"

spring:
  profiles:
    include: 'notification'
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:voting
    username: sa
    password:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  data:
    rest:
      return-body-on-create: true
      base-path: /api
      default-page-size: 5

#  security:
#    user:
#      name: user
#      password: user
#      roles: USER
logging:
  level:
    root: WARN
    com.example.sboot.*: TRACE
    org.springframework.security.web.FilterChainProxy: DEBUG

  # Jackson Serialization Issue Resolver
#  jackson:
#    visibility:
#      field: any
#      getter: none
#      setter: none
#      is-getter: none
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
