create table user_role
(
    user_id integer not null,
    role    varchar(255)
);


create table users
(
    id         integer generated by default as identity,
    email      varchar(128) not null,
    first_name varchar(128),
    last_name  varchar(128),
    password   varchar(256),
    primary key (id)
);